data_path:
- /home/wenjun/franka_calibrate/data/fr3_right/centerright_1
- /home/wenjun/franka_calibrate/data/fr3_right/centerright_2
- /home/wenjun/franka_calibrate/data/fr3_right/centerright_3
- /home/wenjun/franka_calibrate/data/fr3_right/centerleft_1
- /home/wenjun/franka_calibrate/data/fr3_right/centerleft_2
- /home/wenjun/franka_calibrate/data/fr3_right/centerleft_3
- /home/wenjun/franka_calibrate/data/fr3_right/random_1
- /home/wenjun/franka_calibrate/data/fr3_right/random_2
- /home/wenjun/franka_calibrate/data/fr3_right/random_3
end_effector: ball_link
number_samples: null
offset_distance: 0.05
regularizer: 0.0001
robot-name: fr3_right
root_link: base_link
saving_steps: true
urdf: fr3
variance_noise: 0.0
